### ISSUE TITLE
Not functioning in Tinkerer's Quilt as expected

### ISSUE THREAD

**Issue by Xkeeper0** [sisby-folk/drogstyle#1]
I recently set up a Tinkerer's Quilt 1.19 server and some clients. Everything seems to be working except drogstyle; display names and colors don't seem to be taking effect.

The server doesn't seem to output any logs, but here's a GIF showing the commands being put in but the display name not changing:

![javaw_20230827-174049](https://github.com/sisby-folk/drogstyle/assets/1077535/1f17d49b-aff4-4dce-903c-b1cad86c5034)

**Comment by sleepingdragoninn** [comment]
Asked patbox - it's a bug in styled chat 2.0.3 that isn't in 2.0.2, so we've gone in and downgraded that on edge now - have fun!
