### ISSUE TITLE
[suggestion] Port a lost drogtor the nickinator feature

### ISSUE THREAD

**Issue by V-lpen** [sisby-folk/drogstyle#2]
Oh hi again :D I have a suggestion for this mod, that could just be a config option to make sure people can choose if they want it or not
But a feature I really miss from Drogtor the Nickinator is when a written book & quill was signed, it would apply the nickname to the signature, rather than the players username.

Could this be ported to Drogstyle by any chance?
thank you again :D have a nice day

**Comment by sleepingdragoninn** [comment]
I'd ask this over at [styled nicknames](https://github.com/Patbox/StyledNicknames)! I'm unsure why display name isn't used for books, but if anyone has a say it changing that, it's patbox ^^
